#ifndef __SQM_H__
#define __SQM_H__

#include <vector>
#include <string>
#include <semaphore.h>
#include <memory.h>
#include "singleton.h"
#include "dkBaseType.h"
using namespace std;

#define COUNTER_SIZE 512
#define SIZE_OF_INT 4

#define ReadingHistoryFile "/mnt/us/system/reading.dk"
#define FileIDs "/mnt/us/system/readingIDs.dk"

extern sem_t SQMActionSem;//行为变量和写入文件的信号锁
extern sem_t SQMCounterSem;//计数器变量和写入文件的信号锁

#define SQM_ACTION_LIST(MACRO_NAME)                     \
    MACRO_NAME(HOMEPAGE_SELECTBOOK_SHORTCUT)            \
    MACRO_NAME(HOMEPAGE_PAGEUPDOWN_JUMP_SHORTCUT)       \
    MACRO_NAME(HOMEPAGE_SORT_READ_RECENT)               \
    MACRO_NAME(HOMEPAGE_SORT_ADDED_RECENT)              \
    MACRO_NAME(HOMEPAGE_SORT_BOOKNAME)                  \
    MACRO_NAME(HOMEPAGE_SEARCH_PINYIN)                  \
    MACRO_NAME(HOMEPAGE_SEARCH_BOOKNAME)                \
    MACRO_NAME(HOMEPAGE_SEARCH_KEYWORD)                 \
    MACRO_NAME(HOMEPAGE_SEARCH_TAG)                     \
    MACRO_NAME(HOMEPAGE_MENU)                           \
    MACRO_NAME(HOMEPAGE_MENU_WIFI_START)                \
    MACRO_NAME(HOMEPAGE_MENU_WIFI_STOP)                 \
    MACRO_NAME(HOMEPAGE_MENU_91SEARCH)                  \
    MACRO_NAME(HOMEPAGE_MENU_DOWNLOAD)                  \
    MACRO_NAME(HOMEPAGE_MENU_SETTINGS)                  \
    MACRO_NAME(HOMEPAGE_MENU_CURRENTBOOK_DELETE)        \
    MACRO_NAME(HOMEPAGE_MENU_CURRENTBOOK_BOOKMARK)      \
    MACRO_NAME(HOMEPAGE_MENU_CURRENTBOOK_ABOUT)         \
    MACRO_NAME(HOMEPAGE_MENU_WIFIMANAGEMENT)            \
    MACRO_NAME(HOMEPAGE_BOOKLIST_LEFTKEY)               \
    MACRO_NAME(HOMEPAGE_BOOKLIST_RIGHTKEY)              \
    MACRO_NAME(WIFIPAGE_REFRESH)                        \
    MACRO_NAME(WIFIPAGE_MANUAL_ADD)                     \
    MACRO_NAME(WIFIPAGE_CONNECT_SUCCEED)                \
    MACRO_NAME(WIFIPAGE_CONNECT_FAILED)                 \
    MACRO_NAME(WIFI_CONNECT_START)                      \
    MACRO_NAME(WIFI_CONNECT_END)                        \
    MACRO_NAME(AUTOUPDATE_START)                        \
    MACRO_NAME(AUTOUPDATE_END)                          \
    MACRO_NAME(AUTOUPDATE_SUCCEED)                      \
    MACRO_NAME(AUTOUPDATE_FAILED)                       \
    MACRO_NAME(DOWNLOADPAGE_TASKLIST_LEFTKEY)           \
    MACRO_NAME(DOWNLOADPAGE_TASKLIST_RIGHTKEY)          \
    MACRO_NAME(DOWNLOADPAGE_TASKLIST_LEFTKEY_START)     \
    MACRO_NAME(DOWNLOADPAGE_TASKLIST_LEFTKEY_STOP)      \
    MACRO_NAME(DOWNLOADPAGE_TASKLIST_LEFTKEY_PAUSE)     \
    MACRO_NAME(DOWNLOADPAGE_TASKLIST_LEFTKEY_DELETE)    \
    MACRO_NAME(DOWNLOADPAGE_TASKLIST_LEFTKEY_READ)      \
    MACRO_NAME(DKREADERPAGE_OPEN)                       \
    MACRO_NAME(DKREADERPAGE_CLOSE)                      \
    MACRO_NAME(DKREADERPAGE_OPEN_BOOKMARK_PAGE)         \
    MACRO_NAME(DKREADERPAGE_BOOKMARK_ADD)               \
    MACRO_NAME(DKREADERPAGE_BOOKNOTE_ADD)               \
    MACRO_NAME(DKREADERPAGE_PAGE_JUMP)                  \
    MACRO_NAME(DKREADERPAGE_SEARCH_OPEN)                \
    MACRO_NAME(DKREADERPAGE_DICT_OPEN)                  \
    MACRO_NAME(DKREADERPAGE_START_AUTO_PAGE_DOWN)       \
    MACRO_NAME(DKREADERPAGE_BOOK_INDEX_OPEN)            \
    MACRO_NAME(DKREADERPAGE_PDF_SMART_STRIP_EDGE)       \
    MACRO_NAME(DKREADERPAGE_START_AUDIO_PLAYER)         \
    MACRO_NAME(DKREADERPAGE_AADIALOG)                   \
    MACRO_NAME(DKREADERPAGE_AADIALOG_FONTSIZECHANGE_1)  \
    MACRO_NAME(DKREADERPAGE_AADIALOG_FONTSIZECHANGE_2)  \
    MACRO_NAME(DKREADERPAGE_AADIALOG_FONTSIZECHANGE_3)  \
    MACRO_NAME(DKREADERPAGE_AADIALOG_FONTSIZECHANGE_4)  \
    MACRO_NAME(DKREADERPAGE_AADIALOG_FONTSIZECHANGE_5)  \
    MACRO_NAME(DKREADERPAGE_AADIALOG_LAYOUTCHANGE_1)    \
    MACRO_NAME(DKREADERPAGE_AADIALOG_LAYOUTCHANGE_2)    \
    MACRO_NAME(DKREADERPAGE_AADIALOG_LAYOUTCHANGE_3)    \
    MACRO_NAME(DKREADERPAGE_AADIALOG_FONTCOLOR_1)       \
    MACRO_NAME(DKREADERPAGE_AADIALOG_FONTCOLOR_2)       \
    MACRO_NAME(DKREADERPAGE_AADIALOG_FONTCOLOR_3)       \
    MACRO_NAME(DKREADERPAGE_AADIALOG_FONTCOLOR_4)       \
    MACRO_NAME(DKREADERPAGE_AADIALOG_FONTCOLOR_5)       \
    MACRO_NAME(DKREADERPAGE_FONTSIZE_CHANGE_IN_PIXEL)   \
    MACRO_NAME(91SEARCHPAGE_OPEN)                       \
    MACRO_NAME(91SEARCHPAGE_ABOUTPAGE_DOWNLOAD)         \
    MACRO_NAME(91SEARCHPAGE_ABOUTPAGE_READ)             \
    MACRO_NAME(DOWNLOADTASK_BOOK_START)                 \
    MACRO_NAME(DOWNLOADTASK_BOOK_END)                   \
    MACRO_NAME(DOWNLOADTASK_BOOK_END_SUCCEED)           \
    MACRO_NAME(DOWNLOADTASK_BOOK_END_FAILED)            \
    MACRO_NAME(SETTINGPAGE_OPEN)                        \
    MACRO_NAME(SETTINGPAGE_SYSTEM_REBOOT)               \
    MACRO_NAME(SETTINGPAGE_SYSTEM_SWITCH_KINDLE)        \
    MACRO_NAME(SETTINGPAGE_SYSTEM_SWITCH_DUOKAN)        \
    MACRO_NAME(SETTINGPAGE_READ_REPAINTALL)             \
    MACRO_NAME(SETTINGPAGE_FONTSIZECHANGE_1)            \
    MACRO_NAME(SETTINGPAGE_FONTSIZECHANGE_2)            \
    MACRO_NAME(SETTINGPAGE_FONTSIZECHANGE_3)            \
    MACRO_NAME(SETTINGPAGE_FONTSIZECHANGE_4)            \
    MACRO_NAME(SETTINGPAGE_FONTSIZECHANGE_5)            \
    MACRO_NAME(SETTINGPAGE_LAYOUTCHANGE_1)              \
    MACRO_NAME(SETTINGPAGE_LAYOUTCHANGE_2)              \
    MACRO_NAME(SETTINGPAGE_LAYOUTCHANGE_3)              \
    MACRO_NAME(SETTINGPAGE_IME_PINYIN)                  \
    MACRO_NAME(SETTINGPAGE_IME_WUBI)                    \
    MACRO_NAME(SETTINGPAGE_IME_BIG5)                    \
    MACRO_NAME(SETTINGPAGE_IME_CANGJIE)                 \
    MACRO_NAME(SETTINGPAGE_UPDATE)                      \
    MACRO_NAME(SETTINGPAGE_UNINSTALL)                   \
    MACRO_NAME(SETTINGPAGE_COPYRIGHT)                   \
    MACRO_NAME(SETTINGPAGE_IME_LATIN)                   \
    MACRO_NAME(SETTINGPAGE_SERIALIZEDBOOK_AUTO_UPDATE)  \
    MACRO_NAME(SETTINGPAGE_SERIALIZEDBOOK_MANUAL_UPDATE) \
    MACRO_NAME(SETTINGPAGE_SET_ENGLISH_FONT)            \
    MACRO_NAME(SETTINGPAGE_SET_LOCAL_FONT)              \
    MACRO_NAME(SETTINGPAGE_SET_CHINESE_FONT)            \
    MACRO_NAME(DKREADERPAGE_MENU_TXT_AUTO_CHAPTERING)   \
    MACRO_NAME(SETTINGPAGE_DK_SCREENSAVER)              \
    MACRO_NAME(SETTINGPAGE_USER_SCREENSAVER)            \
    MACRO_NAME(SYSTEM_BOOT)                             \
    MACRO_NAME(HOMEPAGE_MENU_QIUSHIBAIKE)               \
    MACRO_NAME(QIUSHIBAIKEPAGE_BTN_REFRESH)             \
    MACRO_NAME(HOMEPAGE_SORT_DIRECTORY)                 \
    MACRO_NAME(SETTINGPAGE_SET_DISABLESCREENPASSWORD)   \
    MACRO_NAME(SETTINGPAGE_SET_ENABLESCREENPASSWORD)    \
    MACRO_NAME(PAGE_MENU_QUERYDICTIONARY)               \
    MACRO_NAME(SETTINGPAGE_SET_PDFRENDERBLACK)          \
    MACRO_NAME(SETTINGPAGE_SET_PDFRENDERNONBLACK)       \
    MACRO_NAME(BOOKREADER_FORMAT_TXT)                   \
    MACRO_NAME(BOOKREADER_FORMAT_PDF)                   \
    MACRO_NAME(BOOKREADER_FORMAT_ZIP)                   \
    MACRO_NAME(BOOKREADER_FORMAT_RAR)                   \
    MACRO_NAME(BOOKREADER_FORMAT_EPUB)                  \
    MACRO_NAME(BOOKREADER_FORMAT_SERIALIZED)            \
    MACRO_NAME(BOOKREADER_FORMAT_UNKNOWN)               \
    MACRO_NAME(KEYBOARD_USAGE_LEFTPAGEUP)               \
    MACRO_NAME(KEYBOARD_USAGE_LEFTPAGEDOWN)             \
    MACRO_NAME(KEYBOARD_USAGE_RIGHTPAGEUP)              \
    MACRO_NAME(KEYBOARD_USAGE_RIGHTPAGEDOWN)            \
    MACRO_NAME(READINGHISTORY_STATISTICS)               \
    MACRO_NAME(READINGHISTORY_RESET)                    \
    MACRO_NAME(ENTERFOLDER_BYRIGHTARROWKEY)             \
    MACRO_NAME(ENTERFOLDER_BYENTERKEY)                  \
    MACRO_NAME(BOOKREADER_TTS)                          \
    MACRO_NAME(BOOKREADER_COMMENTS)                     \
    MACRO_NAME(BOOKREADER_EMAILPUSH)                    \
    MACRO_NAME(BOOKREADER_RENAMEBOOK)                   \
    MACRO_NAME(BOOKREADER_RENAMEFOLDER)                 \
    MACRO_NAME(BOOKREADER_FORMAT_MOBI)                  \
    MACRO_NAME(DKREADERPAGE_BOOKCOMMENT_ADD)            \
    MACRO_NAME(DKREADERPAGE_PDF_CUSTOM_STRIP_EDGE)      \
    MACRO_NAME(DKREADERPAGE_PDF_REARRANGE)              \
    MACRO_NAME(DKREADERPAGE_PDF_NORMAL_MODE)            \
    MACRO_NAME(DKREADERPAGE_PDF_SCREEN_HORIZONTAL)      \
    MACRO_NAME(DKREADERPAGE_PDF_ADAPTIVE_WIDTH)         \

#define DEFINE_SQM_LIST_ENUM(a)                         \
        SQM_ACTION_##a,


enum SQM_ACTIONS
{
        SQM_ACTION_LIST(DEFINE_SQM_LIST_ENUM)
        SQM_ACTION_COUNT
};


class SQM 
{
    SINGLETON_H(SQM);//做单例
public:
    int LogEvent(int iActionId, string strMessage);
    int IncCounter(int iActionId);
    int Flush();
private:
    SQM();
    ~SQM();
    vector<void*>   ActionData;
    static int      g_rgCountData[COUNTER_SIZE];
    static char     g_rgkszSQMEventName[ COUNTER_SIZE ][128];
    static int      nCounterCount; 
    void FlushCounter();
    void FlushAction(); 
};

#endif
